#include <Ice/Ice.h>
#include "Joystick.h"  // Generated by slice2cpp
#include "ClientThread.hpp"
#include "CarDataI.hpp"
#include <iostream>
#include <thread>

int main(int argc, char* argv[]) {
    // Start the client in a separate thread
    ClientThread client(argc, argv);    // This will start the client in a thread

    // Set joystick state
    client.setJoystickValue(true);
    std::cout << "Joystick state set to: true" << std::endl;

    // Get joystick state
    bool joystickState = client.getJoystickValue();
    std::cout << "Joystick state retrieved: " << joystickState << std::endl;

    return 0;
}
