name: Move Issue to In Progress

on:
  create:
    branches:
      - '*'

jobs:
  move-to-in-progress:
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number
        id: extract_issue
        run: |
          BRANCH_NAME="${{ github.event.ref }}"
          if [[ $BRANCH_NAME =~ ^([0-9]+)-issue ]]; then
            echo "issue_number=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          fi

      - name: Move Issue to In Progress
        if: steps.extract_issue.outputs.issue_number != ''
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueNumber = Number(process.env.ISSUE_NUMBER)
            const projectNumber = 42
            const inProgressColumnName = 'In Progress'

            // Get project details
            const projects = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            })

            const project = projects.data.find(p => p.number === projectNumber)

            // Get columns in the project
            const columns = await github.rest.projects.listColumns({
              project_id: project.id
            })

            const inProgressColumn = columns.data.find(col => col.name === inProgressColumnName)

            // Create a project card for the issue
            await github.rest.projects.createCard({
              column_id: inProgressColumn.id,
              content_id: issueNumber,
              content_type: 'Issue'
            })
